# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://psdevuk.github.io/
title: Adam Bacon
email: adambacon1@hotmail.com
author: Adam Bacon
description: > # "Write an awesome description for your new site here.
  This site is all about me and links to my other sites I have.
copyright: "Copyright &copy; 2019 Adam Bacon. All Rights Reserved."
credits: "Credits: Adam Bacon"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/psdevuk
  - title: github
    url: https://github.com/psDevUK
  - title: linkedin
    url: https://www.linkedin.com/in/adam-bacon-993009100/
